name: Deploy to main

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Install dependencies Maven
        run: mvn install
      
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
        
      - name: Run tests Maven
        run: mvn test

      - name: Deploy to main
        if: ${{ success() }}
        run: |
          git checkout main
          git merge develop
          git push
